#!/usr/bin/env python3
"""Enforce "one app per PR" + protect repo infrastructure from app-submission PRs.

Takes the list of files changed in a PR (one path per line on stdin - the
workflow feeds this via `git diff --name-only <base> <head>`) and checks:
  - every changed file lives inside exactly one top-level app directory,
  - none of the changed files are protected paths (.github/, scripts/,
    index.json, README.md, .gitignore) - those are either bot-managed
    (index.json, regenerated by CI on merge) or repo infrastructure that
    should be changed by its own dedicated PR, not bundled into an app
    submission (mirrors Nicolai Electronics' app-repository's
    prevent_changes.yml, which auto-closes PRs touching .github/.validator).

Exit code is non-zero on any violation.
"""
import os
import sys

PROTECTED_PATHS = {".github", "scripts", "index.json", "README.md", ".gitignore"}


def top_level(path):
    return path.split("/", 1)[0]


def main():
    files = [line.strip() for line in sys.stdin if line.strip()]
    if not files:
        print("::error::no changed files found in this PR")
        return 1

    touched_protected = sorted({f for f in files if top_level(f) in PROTECTED_PATHS})
    if touched_protected:
        print(
            "::error::this PR touches repository infrastructure, not just an app "
            f"submission: {', '.join(touched_protected)}. Infra changes (CI, "
            "validation scripts, index.json, README) need their own dedicated PR - "
            "index.json in particular is auto-regenerated by CI on merge, never "
            "hand-edited."
        )
        return 1

    app_dirs = sorted({top_level(f) for f in files})
    if len(app_dirs) == 0:
        print("::error::no app directory changes found")
        return 1
    if len(app_dirs) > 1:
        print(
            f"::error::this PR touches {len(app_dirs)} app directories "
            f"({', '.join(app_dirs)}) - one app per PR, please split this up."
        )
        return 1

    print(f"OK: PR touches exactly one app directory ({app_dirs[0]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
